### PR TITLE
Remove six

### LINKED ISSUE #21: Six still needed?
Looks like this slipped through the latest Python 3 only upgrade.
https://github.com/zopefoundation/zc.relation/blob/ddc85334b389110f1ce6307935360edcadebd5f7/setup.py#L63

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #21

### CODE REVIEW

**Review by jensens — APPROVED** [review]

**Comment by jensens** [comment]
Btw. is this by intend? 
screenshot_2023-03-31_12:04:56_selection

**Comment by ale-rt** [comment]
I see that also in other PRs in different packages, e.g.: https://github.com/zopefoundation/zope.copy/pull/10

I did not invest time in checking more

**Comment by jensens** [comment]
Ok, unrelated, lets ignore here.

**Comment by icemac** [comment]
> Btw. is this by intend?
> screenshot_2023-03-31_12:04:56_selection

@jensens We skip the pull request tests for branches inside the source repository, so the tests do not run twice.

**Pull request merged**
